# Generated by Django 3.2.3 on 2021-05-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='approved',
            new_name='deleted',
        ),
    ]
