# Generated by Django 3.2.3 on 2021-09-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210914_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
